name: test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run tests
        run: |
          make test
